/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndstillingerRouteImport } from './routes/indstillinger'
import { Route as ArkivRouteImport } from './routes/arkiv'
import { Route as IndexRouteImport } from './routes/index'

const IndstillingerRoute = IndstillingerRouteImport.update({
  id: '/indstillinger',
  path: '/indstillinger',
  getParentRoute: () => rootRouteImport,
} as any)
const ArkivRoute = ArkivRouteImport.update({
  id: '/arkiv',
  path: '/arkiv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arkiv': typeof ArkivRoute
  '/indstillinger': typeof IndstillingerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arkiv': typeof ArkivRoute
  '/indstillinger': typeof IndstillingerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arkiv': typeof ArkivRoute
  '/indstillinger': typeof IndstillingerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arkiv' | '/indstillinger'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arkiv' | '/indstillinger'
  id: '__root__' | '/' | '/arkiv' | '/indstillinger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArkivRoute: typeof ArkivRoute
  IndstillingerRoute: typeof IndstillingerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/indstillinger': {
      id: '/indstillinger'
      path: '/indstillinger'
      fullPath: '/indstillinger'
      preLoaderRoute: typeof IndstillingerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arkiv': {
      id: '/arkiv'
      path: '/arkiv'
      fullPath: '/arkiv'
      preLoaderRoute: typeof ArkivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArkivRoute: ArkivRoute,
  IndstillingerRoute: IndstillingerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
